### ISSUE TITLE
Entity list header: drop the title, give the row to search, actions and the pin

### ISSUE THREAD

**Issue by jon-whiteroomsoftware** [jon-whiteroomsoftware/PXLBLZ-IDE#976]
## Parent

Layout sequence agreed with Jon (#965 top bar, #966 entity drawer, #967 Show over/under, #968 panels). Follow-on to #965 and #966, raised by Jon on 2026-09-07 after they shipped.

## What to build

Remove the entity list's title and give its row to the controls that were squeezed beside it. With the place control in the top bar (#965) the list title ("Shows", "Patterns", …) repeats it. Prototype, section 03 of the drawer prototype (self-contained HTML): https://gist.github.com/jon-whiteroomsoftware/6e2f3ad218533d0d4d8f05d8318be8f7 . Raw: https://gist.githubusercontent.com/jon-whiteroomsoftware/6e2f3ad218533d0d4d8f05d8318be8f7/raw/entity-list-drawer-prototype.html .

- **No title.** `RailEntityHeader` drops its `h2`; the accessible name of the list region stays (aria-label from the place), so screen readers keep it.
- **Row one, every type, 40 px:** a real search field taking the width only for types that already support search (Patterns, Shows, Maps; placeholder "Search patterns", "Search shows", …; always visible; Escape clears; typeahead as today's `RailFilterBar`), then the type's create actions as 26 px bordered icon buttons (New folder where the type has folders, New entity), then the housing control at the far right: Pin (pressed when pinned; disabled below 980 px as today). There is no Close button: an unpinned drawer closes on Escape, click-away, choosing an entity, or the mouse-out timer (#966), and a separate button changed the row's control count between states (Jon, 2026-09-07). Tooltips and aria-labels as today's `HeaderAction`.
- **Row two, 30 px, only when it has content:** the type's existing dimension filter (Patterns and Maps; All / 1D / 2D / 3D, preserving current filtering semantics) and a count at the right that reads "N patterns" idle and "N of M" while filtering or searching. Types without a filter (Shows, Controllers, Mixins, Libraries) show row two only while a search is typed, with the count alone.
- **Existing search is a field, not a toggle.** Today's expand-on-click search becomes a permanent field; the search-icon HeaderAction goes. Controllers, Mixins and Libraries currently have no search and gain none; no placeholder or disabled search field is added. Their current action controls and pin remain right-aligned.
- **Per type: preserve the current functionality exactly (Jon, 2026-09-07).** Patterns: dimension filter, Open pattern from .epe file, Add pattern menu (New pattern, New folder). Shows: Add show menu (New show, Import Show file…, New folder, conditional New show from the Controller profile). Maps: dimension filter, Add map menu (New map, New folder). Mixins and Libraries: Add menu (New entity, New folder). Controllers: Add folder menu (New folder) only; do not invent New profile. Preserve authentication/availability conditions. Compact menus keep these actions reachable in the reordered row; prototype omissions are mistakes, not feature removals. Verify the current slots again before editing.

## Limits

- Layout/reordering only. Every existing per-entity action, import path, dimension filter, conditional action and authentication/availability gate is preserved. The tree, drag-move, rename, trash and drawer behaviour (#966) are unchanged.
- No contextual label in place of the title; the count and the top-bar place control carry orientation.
- Minimum list width 240 px (Jon approved widening the minimum on 2026-09-07); row one must fit search (min 120 px where search already exists), existing action controls, and pin without wrapping. Preserve overlay/docked behavior and clamp remembered widths to the supported minimum.

## Acceptance criteria

- [ ] No list shows a title; every list's region keeps an accessible name equal to the place.
- [ ] Row one lays out per type as specified, pinned and unpinned, at the list's minimum width; the pin is the only housing control and the row's control count does not change between pinned and unpinned; Escape and click-away still close an unpinned drawer.
- [ ] Existing search is always visible for Patterns, Shows and Maps; typing filters as today; Escape clears. Search adds a count row when none was already needed; filter rows remain when search clears. Controllers, Mixins and Libraries gain no search.
- [ ] Patterns' dimension pills work as today and the count reads "N of M" while a dimension other than All is selected.
- [ ] Existing Playwright suites pass with locators updated, not weakened (the title-based locators change).

## Required proof

UI proof record in `.wrsp/ui-proof/` from the real Studio at the implementation commit: Patterns pinned with the pills, Patterns unpinned open with a search typed, Shows pinned, at 1440 px and at the list's minimum width. Attach with a `Proof:` line before closing.

## Tests

- Component: header per type (actions present/absent), pin/close state, search field behaviour, row-two visibility and count text.
- e2e (`npm run test:e2e`, app shell): search from the field on Patterns and Shows; pills; pin and close; no title text in any list.

## Implementation entry points

`src/components/rail/RailPrimitives.tsx` (`RailEntityHeader`, `HeaderAction`, `RailFilterBar`), `src/components/PatternList.tsx` and the other list panes' header action slots, `src/components/DimPills.tsx`.

## Docs impact

Feature Guide section 2 (Studio orientation and the list).

## Progress

Status: in progress. Claimed 2026-09-07 by Codex layout coordinator (task 01a07c33-32e2-7f10-b51a-278fc04c5798); execution worker gpt-6-astra at low under the current execution policy. Source-level design sanity check supports the accepted pin-only header. Preserve the existing busy-state Escape ordering (clear active search before drawer dismissal) and verify existing create actions per type. Prototype visual inspection was blocked by the browser file-URL security policy; real-route browser proof remains mandatory. Coordinator owns final suites, review, and landing.

### Coordinator visual review — supplied captures, 2026-09-07

Visual sanity gate passed after inspecting the user-supplied `entity-list-drawer-prototype/07-list-header-redesign.png`: search/actions/pin maintain the accepted header structure across pinned, unpinned and searching states. Worker resumed/started on gpt-6-astra Low. Real application interaction and minimum-width proof remain implementation requirements.

### Jon clarification — functionality preservation, 2026-09-07

Jon explicitly confirmed this is only a reordering and relayout, with no change to the current set of tools per entity. Prototype differences are mistakes. The corrected per-type inventory above is verified against `src/components/rail/*RailSection.tsx`; the implementation must preserve those existing paths and conditions, including Maps dimension filtering. Tests must verify each current action remains reachable and unavailable actions retain their existing gates.

### Jon clarification — search availability, 2026-09-07

Jon explicitly chose **Preserve current search availability**. Permanent search applies only to Patterns, Shows and Maps. Controllers, Mixins and Libraries retain their lack of search. This supersedes the original universal-search wording and corresponding prototype fields.

### Jon constraint — keyboard ownership, 2026-09-07

Preserve existing keyboard controls and event ownership. In particular, Space is preview play/pause in many views; prior special handling is authoritative. Do not introduce shortcuts or blanket event interception that overrides existing behavior. Read `docs/reference/PXLBLZ Keyboard Shortcuts.md` and the applicable `studioControlOwnsKeyboardEvent`, `showControlOwnsKeyboardEvent`, drawer/Show Escape ownership before changes. Focused checks must preserve Space behavior on changed chrome, native text editing (including spaces), documented control-specific exceptions, and existing Escape peeling. This is preservation, not a new keyboard design.

### Jon clarification — minimum width, 2026-09-07

Jon approved widening the minimum because the collapsible list overlays the workspace. The coordinator selected 240 px to fit the 120 px search and existing controls with spacing. Replace the prior 184 px minimum and its test expectation; prove pinned and unpinned rows at 240 px, with every existing tool reachable and no wrapping.

### Keyboard regression disposition — 2026-09-07

A focused real-route test found that Space on the list pin in Show mode activates the pin instead of playback. The base header lacked the existing `data-studio-space-preview` marker, while Show mode uses its own keyboard owner. The bounded repair applies the existing playback marker to reordered header action triggers and dimension controls; it adds no listener or shortcut and leaves text fields and open menu choices under their existing local rules. Required evidence: Space toggles playback once without activating pin/create/filter on Pattern and Show routes; Enter still operates those controls. This follows Jon’s explicit keyboard-preservation requirement and the documented playback contract.

## Current implementation candidate — 2026-09-07

The complete corrected implementation scope is claimed by `40c5c4ffbfd17130038bdb9be52bc899f52bc30a` on `codex/issue976`, based on `ea6935ba1c6bcc41e71e562a7809b77aba05b70a`. The clean candidate preserves every existing per-type action, filter, search availability and conditional gate. It implements the approved 240 px minimum and measures the header at exactly 40 px. Existing playback markers enforce Space ownership on reordered header chrome; no global keyboard listener/policy changed.

Focused evidence: 100 component/geometry cases, 101 App cases, targeted authenticated desktop/narrow/drawer/keyboard flows, lint and TypeScript passed. Six committed captures were inspected by the worker at code `618c013249216a69e78d2c2f9614ad9f457fd146`, with no console/runtime errors and exact height/overflow assertions. Root inspected the preceding visual set; refreshed final evidence will be reviewed after rebase. Feature Guide updated; no domain-language or keyboard-doc change.

Next: rebase after #977 lands, refresh proof at the rebased code tip, collect required exact-tip full suites, run native review and land. No native approval, landing or publication is claimed.

Proof: six `.wrsp/ui-proof/976-*.json` records and their committed captures; standalone UI-proof gate passes for this candidate. `📦 implemented` identifies the full-scope branch claim only.

### Local landing and UX testing — 2026-09-07

Jon requests each reviewed ticket/slice land on local main as soon as its checks pass so he can perform UX testing. Hold all pushes/publication until Jon gives the go-ahead after that testing.

### Implemented-label gate — Jon, 2026-09-07

Apply `📦 implemented` only after the whole ticket’s feature has landed on local main. A candidate branch or a partial slice does not qualify. Remove `in-progress` once the whole implementation has landed; UX acceptance and publication remain separate. This overrides the earlier candidate-commit label convention for this work.

### Whole-ticket landing — 2026-09-07

The complete #976 feature landed on local main at `d49d53a02fb9237b907e667ae354485cabd8a9f9`: titleless40px headers, permanent search only where previously available, existing actions preserved, filters/counts below, trailing pin, and240px minimum. All four authoritative final suites passed at this exact tip. Native `claude-fable-5-1` High review approved `855c1332..d49d53a0` with no findings. Available at http://localhost:5174/PXLBLZ-IDE/ for UX testing. `📦 implemented` now applies because whole scope is landed; `in-progress` removed. No push; publication held for Jon’s UX go-ahead.

Proof: the six `.wrsp/ui-proof/976-*.json` records and PNG captures at `d49d53a0` cover desktop/minimum/pinned/overlay/narrow/search states. Focused and final browser checks preserve existing tools/search, Space/Enter/Escape behavior, and #978 lesson focus correction. Feature Guide updated; domain and keyboard behavior preserved.

Residual test observation: the existing drawer drag setup passed this final tip but failed intermittently on later #979’s final run; investigated with #979 rather than claiming the readiness change conclusively solved its cause.

**Comment by jon-whiteroomsoftware** [comment]
Prototype updated to make the pin the only housing control and document unpinned-drawer dismissal via Escape, click-away, entity selection, or timer. This advances the agreed design, but does not implement or verify the header behavior and acceptance criteria in the application.

**Comment by jon-whiteroomsoftware** [comment]
Commit addresses the header reflow, permanent search, filters/counts, right-aligned pin, preserved actions, and 240 px minimum width, with updated component and Playwright tests. Closure still needs proof that the acceptance criteria hold in the running UI and the existing Playwright suites pass; the X-E2E trailer records test changes, not successful execution.

**Comment by jon-whiteroomsoftware** [comment]
Updated App.test.tsx to preserve click-away dismissal coverage through the editor pane after opening the entity overlay. This supports #976’s drawer-behavior requirement, but this test-only commit does not establish completion of the header layout, per-type controls, search/filter behavior, or required Playwright proof.

**Comment by jon-whiteroomsoftware** [comment]
Added real-route screenshot proof for Patterns and Shows at desktop and minimum list widths, including filtered unpinned and narrow overlays with isolated synthetic authentication. This proof-only commit does not establish that all per-type behavior, accessibility requirements, and required Playwright suites pass; #976 remains open.

**Comment by jon-whiteroomsoftware** [comment]
This commit addresses the 40 px header-row requirement under Studio text scaling and adds a rendered-height assertion to the narrow-route E2E check. The supplied text does not establish completion of the remaining layout, search, action-preservation, accessibility, and drawer requirements or confirm passing suites. Keep the issue open.

**Comment by jon-whiteroomsoftware** [comment]
Refreshed six real-route UI captures asserting 40 px header height and no overflow under synthetic authentication, covering Patterns and Shows across pinned, unpinned, minimum-width, and narrow search states. This adds layout proof, but the commit alone does not establish all per-type behavior, preserved actions and accessibility, or passing Playwright suites required to close #976.

**Comment by jon-whiteroomsoftware** [comment]
The commit addresses the header reflow, permanent search, dimension pills and counts, action preservation, and 240 px minimum width, with updated component and Playwright tests. The supplied text does not establish that the required Playwright suites passed or provide browser proof of minimum-width layout and pinned/unpinned behavior. Keep open pending that verification.

**Comment by jon-whiteroomsoftware** [comment]
Updated the app-shell test to exercise click-away dismissal through the editor pane after opening the entity overlay, covering part of #976’s drawer-dismissal acceptance criterion. This test-only commit does not establish completion of the header layout, per-type controls, search/count behavior, or required verification.

**Comment by jon-whiteroomsoftware** [comment]
Added real-route UI proof for Patterns and Shows at desktop and minimum list widths, including filtered unpinned and narrow overlays. This proof-only commit supports #976, but does not establish implementation of all acceptance criteria, coverage of the remaining entity types, or passing Playwright suites. Keep the issue open.

**Comment by jon-whiteroomsoftware** [comment]
This commit addresses the 40 px header-row requirement under Studio text scaling and adds a rendered-height assertion to the narrow-route E2E check. The supplied text does not establish completion of the remaining layout, search, action-preservation, accessibility, and drawer requirements, or that the required suites passed.

**Comment by jon-whiteroomsoftware** [comment]
Refreshed six real-route UI captures asserting 40 px header height and no header overflow under synthetic authentication. This adds layout proof for Patterns and Shows, but does not establish completion of all per-type behavior, accessibility, action-preservation requirements, or passing Playwright suites. Keep #976 open.

**Comment by jon-whiteroomsoftware** [comment]
Refreshed browser-proof artifacts for Patterns and Shows across pinned desktop, minimum-width, and unpinned/narrow search states on the landed Show workspace base. This commit updates evidence only; the supplied text does not establish that all acceptance criteria are met or that the required Playwright suites pass.

**Comment by jon-whiteroomsoftware** [comment]
Updated E2E checks to scope the missing-map warning to its status and wait for the drawer to hide before the drag gesture, preserving preview and suppression assertions. Focused authenticated import and drawer cases passed three times each. Final suites remain with the coordinator; this commit alone does not establish completion of #976.

**Comment by jon-whiteroomsoftware** [comment]
This commit appears to implement #976’s header reflow, preserve existing controls and search behavior, and raise the minimum width to 240 px. Component and Playwright tests were updated, but the supplied text does not show passing suites or browser proof of the required layouts and interactions. Keep open pending that verification.

**Comment by jon-whiteroomsoftware** [comment]
Updated app-shell test coverage to exercise click-away dismissal through the editor pane after opening the entity overlay, supporting #976’s drawer-dismissal requirement. This test-only commit does not establish completion of the header layout, search, action preservation, or remaining acceptance criteria.

**Comment by jon-whiteroomsoftware** [comment]
Added real-route screenshot proof for Patterns and Shows at desktop and minimum list widths, including filtered unpinned and narrow overlay states. This proof-only commit supports #976, but does not establish completion of all per-type behavior, accessibility requirements, or passing Playwright suites.

**Comment by jon-whiteroomsoftware** [comment]
The commit enforces the 40px header row under Studio text scaling and adds a rendered-height assertion to the narrow-route Playwright check. This addresses the row-height requirement, but the supplied text does not establish completion of the remaining layout, search, action-preservation, accessibility, and drawer criteria or confirm passing suites.

**Comment by jon-whiteroomsoftware** [comment]
Refreshed all six real-route UI proof captures for #976, asserting a 40 px header height and no header overflow under synthetic authentication. This supplies layout evidence, but the commit alone does not establish completion of the remaining acceptance criteria or passing Playwright suites.

**Comment by jon-whiteroomsoftware** [comment]
Refreshed six browser-proof captures and metadata for Patterns and Shows on the landed Show workspace base. This commit updates verification artifacts only; it does not establish that all per-type requirements and Playwright acceptance criteria are complete.

**Comment by jon-whiteroomsoftware** [comment]
Updated the import warning locator to target its specific status and made the drag test wait for the drawer to hide, preserving existing assertions. Focused authenticated import and drawer cases passed three times each. Final suites remain with the coordinator; this commit alone does not demonstrate completion of the full layout scope and acceptance criteria.

**Comment by jon-whiteroomsoftware** [comment]
Refreshed six UI proof captures and their metadata for Patterns and Shows across pinned, minimum-width, and search states. This commit updates verification artifacts only; it does not establish that all acceptance criteria are met or that the required Playwright suites pass.

**Comment by jon-whiteroomsoftware** [comment]
Updated the lesson keyboard interaction test locator for permanent Show search; the commit reports the focused pointer and keyboard test passed. This supports the locator-update acceptance criterion, but does not establish completion of the header layout, per-type behavior, or remaining acceptance criteria.
